### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by FPSUsername** [eastein/dbf2json#1]
Hello, I have an issue and it doesn't work at all:

https://pastebin.com/1DxVr8Rp

The first conversion is done by replacing:
import dbfread -> from dbfread import DBF
dbfread.open( -> DBF(

The second conversion is with the dbf2json file unmodified

Please update this as soon as possible

**Comment by eastein** [comment]
The problem is probably in https://github.com/olemb/dbfread/ not my code.

Can you provide some more info?

* what version of dbfread is installed? I'm using an older version of dbfread (1.0.1) in my requirements file
* can you upload your dbf file? It seems like the version of dbfread you are using can't read it, maybe there is something wrong or a newer version of dbfread would be able to read it
* try installing newer dbfread and see if it works (assuming you are using 1.0.1)

I'll re-open the ticket when you reply.

**Comment by FPSUsername** [comment]
I believe that I use the latest version available. I will downgrade to 1.0.1 as soon as I can.
I wrote an issue ticket here: https://github.com/Polyconseil/libcanardbc/issues/2
That is the tool that I can use with caneton (DBC to JSON), but it has an issue with converting extended frame ids. I also tried to convert with canmatrix and that does the job, but it is sorted differently, so caneton can not use it.

I used busmaster to convert the DBC file to a DBF file
[Downloads.zip](https://github.com/eastein/dbf2json/files/1044303/Downloads.zip)

**Comment by eastein** [comment]
I'm not going to lie, I don't know what any of those software packages you are talking about are.

I can tell you that dbfread 1.0.1 on my system doesn't like the file you uploaded, though.

    (dbf2json)eastein@amontillado ~/git/dbf2json :( master  $ ./dbf2json /home/eastein/Downloads/V10_CAN_ime.dbf
    Traceback (most recent call last):
      File "./dbf2json", line 47, in <module>
        output = [rec for rec in dbfread.open(in_filename)]
      File "/home/eastein/venvs/dbf2json/local/lib/python2.7/site-packages/dbfread/dbf.py", line 142, in __init__
        self._check_headers()
      File "/home/eastein/venvs/dbf2json/local/lib/python2.7/site-packages/dbfread/dbf.py", line 245, in _check_headers
        raise ValueError('Unknown field type: {!r}'.format(field.type))
    ValueError: Unknown field type: u'e'
    (dbf2json)eastein@amontillado ~/git/dbf2json :( master  $

**Comment by eastein** [comment]
Upon looking at the DBF standard a bit (http://www.dbase.com/KnowledgeBase/int/db7_file_fmt.htm) I see that field type E isn't defined there, which I presume is the "extended frames" you are talking about. dbfread is erroring about a field type 'e' not being known.

Newest dbfread (2.0.7) doesn't work either (the following was tested with 2.0.7):

    (dbf2json)eastein@amontillado ~/git/dbf2json :) master  $ !./dbf2
    ./dbf2json /home/eastein/Downloads/V10_CAN_ime.dbf
    /home/eastein/venvs/dbf2json/local/lib/python2.7/site-packages/dbfread/deprecated_dbf.py:52: UserWarning: dbfread.open() has been replaced by DBF() and will be removed in 2.2.
      warnings.warn("dbfread.open() has been replaced by DBF()"
    Traceback (most recent call last):
      File "./dbf2json", line 47, in <module>
        output = [rec for rec in dbfread.open(in_filename)]
      File "/home/eastein/venvs/dbf2json/local/lib/python2.7/site-packages/dbfread/deprecated_dbf.py", line 54, in open
        return DeprecatedDBF(filename, load=True, **kwargs)
      File "/home/eastein/venvs/dbf2json/local/lib/python2.7/site-packages/dbfread/dbf.py", line 123, in __init__
        self._check_headers()
      File "/home/eastein/venvs/dbf2json/local/lib/python2.7/site-packages/dbfread/dbf.py", line 265, in _check_headers
        raise ValueError('Unknown field type: {!r}'.format(field.type))
    ValueError: Unknown field type: 'e'
    (dbf2json)eastein@amontillado ~/git/dbf2json :( master  $ 

I'm also not sure what libcanardbc has to do with my software (which is just a very simple wrapper around dbfread).
