### ISSUE TITLE
dbf2json no se reconoce como un comando interno o externo

### ISSUE THREAD

**Issue by LugerJ** [eastein/dbf2json#2]
tengo instalado el pip -10.0.1, dentro del subdirectorio dbf2json copie una tabla dbf que quiero convertir a json, pero no reconoce el comando dbf2json, soy nuevo en python, que debo hacer?

**Comment by eastein** [comment]
Intente acceder utilizando ./dbf2json en la línea de comandos: solo necesitaba usar este script brevemente, por lo que nunca me molesté en configurar nada para instalar dbf2json en el PATH. Avíseme si eso no funciona y vuelva a abrir el problema. Lo siento, no sé español, así que estoy respondiendo usando Google translate.
